# Site settings
title: Dev Day Conference 
email: "devdayconference@gmail.com"
description: Event for all comunities..
url: "http://devdayconf.github.io"
# baseurl: "/"

# twitter_username: pyladies_mendoza
github_username: PKpacheco

# Build settings
markdown: kramdown

highlighter: green

# Pagination
# paginate: 15
# paginate_path: "/blog/page:num/"



collections:
  home:
    output: true
    permalink: /home/:path/
  organizers:
    output: true
    permalink: /organizers/:path/
  events:
    output: true
    permalink: /events/:path/
  contact:
    output: true
    permalink: /contact/:path/