# Site settings
title: + Con
email: "masconferencia@gmail.com"
description: Event for all.
baseurl: "/"
url: "/mas-con.github.io"
# twitter_username: _devdayconf
# github_username: mas-con

# Build settings
markdown: kramdown

highlighter: grey


collections:
  home:
    output: true
    permalink: /home/:path/
  creator:
    output: true
    permalink: /creator/:path/
  rules:
    output: true
    permalink: /rules/:path/
  events:
    output: true
    permalink: /events/:path/
  contact:
    output: true
    permalink: /contact/:path/